### ISSUE TITLE
【新增功能】

### ISSUE THREAD

**Issue by marklove5102** [liuxingyu521/website-nav#134]
能否提供一个支持显示json内容导航方案。
个人用 用不上seo这些啊。

**Comment by liuxingyu521** [comment]
可否形容再具体一点？

**Comment by marklove5102** [comment]
我之前用onenav，后来用c++模仿了 onenav 的返回数据行为写了个c++后端。
我看你这个项目页面不错。是否能增加展示 服务端返回的json？
我对ts不熟找了很多浏览器插件源码 没啥满意的。
对个人来说 
添加方便，查找方便。精准就够用了又不是提供服务没必要把数据写死.直接展示json数据不好吗。
随着php不断变化 onenav 的部署docker是方便但是也是重量级了，单纯c++程序可以直接部署在算力很小的单片机。
